import Head from "next/head";
import Link from "next/link";
import { Endpoint } from "../services/endpoint";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>API Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to API Book</h1>
        <div className={styles.grid}>
          {Endpoint.map((end, index) => (
            <Link
              key={index}
              href={end.endpoint}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                background:
                  "linear-gradient(to right, #0f0c29, #302b63, #24243e)",
                width: "13rem",
                height: "11rem",
                cursor: "pointer",
              }}
            >
              <h2 className={inter.className}>
                {end.title} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>{end.text}</p>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
